### ISSUE TITLE
Error building clean clone of CU-Events

### ISSUE THREAD

**Issue by Shane7** [CUModSquad/cu-build-tools#46]
In a new clone of CU-Events, after doing a npm and gulp install, gulp publish failed with this error repeated several times:

...cu-events/node_modules/ntypescript/bin/ntypescript.d.ts(1710,15): error TS1110: Type expected.

To fix the error I had to revert to an older version of ntypescript:
npm install ntypescript@1.201511020604.1

**Comment by saddieeiddas** [comment]
I will have a look into this. Will also check other libraries build with a clean install.

**Comment by saddieeiddas** [comment]
can confirm that this happens, I am going to look into what exactly is going wrong and how we can fix going forward

**Comment by saddieeiddas** [comment]
Have found where the issue lies, will have a fix for this soon.

We can remove `ntypescript` completely now, as TypeScript 1.6+ (1.7 now) does what we need it too.

The TSD install, was adding a reference to ntypescript.d.ts for some reason (will look into why that is also) which was causing some errors.
